@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
class Airport<< (B,#FF7700) BusStop >>
class TrainStation << (B,#FF7700) BusStop >>
class CityHall<< (B,#FF7700) BusStop >>
class OldTown<< (B,#FF7700) BusStop >>
class ResidentialTown<< (B,#FF7700) BusStop >>

Airport --- TrainStation : Route-1 [1.0Km]
Airport --- TrainStation : Route-3 [1.0Km]
TrainStation --- CityHall : Route-1 [1.0Km]
OldTown --- CityHall : Route-1 [1.0Km]
ResidentialTown --- OldTown : Route-1 [2.0Km]
Airport --- ResidentialTown : Route-2 [2.0Km]
TrainStation ---OldTown : Route-3 [1.0Km]

@enduml